# Generated by Django 6.0.7 on 2026-07-29 06:56

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text='Введите номер телефона',
                max_length=128,
                null=True,
                region=None,
                verbose_name='Phone Number',
            ),
        ),
    ]
