# Generated by Django 6.0.7 on 2026-07-28 14:47

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text='Введите номер телефона',
                max_length=128,
                null=True,
                region=None,
                unique=True,
                verbose_name='Phone Number',
            ),
        ),
    ]
