# Generated by Django 6.0.7 on 2026-07-28 16:00

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество')),
                ('second_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Фамилия')),
                ('position', models.CharField(blank=True, default='', max_length=150, verbose_name='Должность')),
                (
                    'phone_number',
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text='Укажите номер телефона',
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name='Телефон',
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        help_text='Укажите Email', max_length=254, unique=True, verbose_name='Email пользователя'
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('На работе', 'На работе'),
                            ('Отпуск', 'Отпуск'),
                            ('Больничный', 'Больничный'),
                            ('Выходной', 'Выходной'),
                        ],
                        default='На работе',
                        max_length=15,
                        verbose_name='статус',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        help_text='Укажите руководителя',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='employees',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Руководитель',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, verbose_name='Описание задачи')),
                (
                    'deadline',
                    models.DateTimeField(
                        help_text='Укажите дату и время завершения задачи', verbose_name='Срок выполнения'
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('Создана', 'Создана'), ('Выполняется', 'Выполняется'), ('Завершена', 'Завершена')],
                        default='Создана',
                        max_length=30,
                        verbose_name='Статус задачи',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                (
                    'priority',
                    models.CharField(
                        choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')],
                        default='medium',
                        max_length=10,
                        verbose_name='Приоритет',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tasks',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Руководитель',
                    ),
                ),
                (
                    'parent_task',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subtasks',
                        to='employees.task',
                        verbose_name='Связанная задача',
                    ),
                ),
                (
                    'performer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tasks',
                        to='employees.employee',
                        verbose_name='Исполнитель задачи',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
