# Generated by Django 6.0.7 on 2026-07-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(
                help_text='Укажите Email', max_length=254, unique=True, verbose_name='Email сотрудника'
            ),
        ),
    ]
