# Generated by Django 6.0.7 on 2026-08-01 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='subtasks',
                to='employees.task',
                verbose_name='Связанная задача',
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='performer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='tasks',
                to='employees.employee',
                verbose_name='Исполнитель задачи',
            ),
        ),
    ]
