# Generated by Django 6.0.7 on 2026-08-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_task_parent_task_alter_task_performer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(
                choices=[('Низкий', 'Низкий'), ('Средний', 'Средний'), ('Высокий', 'Высокий')],
                default='Средний',
                max_length=10,
                verbose_name='Приоритет',
            ),
        ),
    ]
